apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: django
    - port: 80
      targetPort: 80
      name: nginx
  selector:
    app: backend
